version: '3'

services:
  jenkins:
    build:
      context: .
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    networks:
      - net


  groovy-executor:
    image: groovy
    volumes:
      - ./tus_scripts_groovy:/scripts
    command: ["groovy", "/scripts/tu_script.groovy"]

networks:
  net:
