version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net

  groovy-app:
    image: groovy:latest
    volumes:
      - $PWD:/app
    working_dir: /app
    networks:
      - net

networks:
  net:
