name: Ejecutar Máquina Virtual en AWS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Ejecutar Máquina Virtual en AWS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CORAIMA_KEY }}
      run: |
        echo "${{ secrets.SSH_CORAIMA_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa prueba2@18.220.141.63

