name: Ejecutar Máquina Virtual en AWS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar llave privada
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CORAIMA_KEY }}" > ~/.ssh/github_actions_key
        chmod 600 ~/.ssh/github_actions_key

    - name: Conectar y ejecutar comando en la Máquina Virtual
      run: ssh -i ~/.ssh/github_actions_key prueba2@18.220.141.63 'comando_a_ejecutar'