name: Ejecutar Máquina Virtual en AWS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Checkout Eddy
      uses: actions/checkout@v4


 